# Generated by Django 5.2.5 on 2025-08-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500)),
                ('p256dh_key', models.CharField(max_length=100)),
                ('auth_key', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('endpoint', 'p256dh_key')},
            },
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
