# Generated by Django 5.2.5 on 2025-08-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotificaciones', '0002_pushsubscription_delete_subscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pushsubscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='token',
            field=models.CharField(default='', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='auth_key',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='p256dh_key',
        ),
    ]
