"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import firebase_admin
import os
import json
from firebase_admin import credentials, initialize_app

firebase_creds = os.getenv("FIREBASE_CREDENTIALS")  # variable de entorno

if firebase_creds:
    cred_dict = json.loads(firebase_creds)
    cred = credentials.Certificate(cred_dict)
    initialize_app(cred)
else:
    raise Exception("No Firebase credentials found")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7r=5*2b=#f-mvyo-*2!^b#s)7h^)ro#xn&6xp@*_smddg9fie3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
CORS_ALLOW_ALL_ORIGINS = True
FIREBASE_SERVICE_ACCOUNT = "pushnotificaciones/fcm.json"  # Ruta al archivo de credenciales de Firebase
ALLOWED_HOSTS = [
    "12b5cbd947fa.ngrok-free.app",
    "localhost",
    "127.0.0.1",
    "django-push.onrender.com",  # 👈 tu dominio de Render
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    'pushnotificaciones'
]
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:4200",
# ]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
VAPID_PUBLIC_KEY = "BFnAa2SC7BbfcmblAHftinu3Wjd_8RlWnzSDp_Fgn8G-QIn79E3OkQioKkQSXa3rFT6sIyG-dA3-8GOiBXk8FHk="
VAPID_PRIVATE_KEY = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg5VUM4s3hG1eovAllT9yMeMa_YWe5E6taYiv6eEG6YRehRANCAARZwGtkguwW33Jm5QB37Yp7t1o3f_EZVp80g6fxYJ_BvkCJ-_RNzpEIqCpEEl2t6xU-rCMhvnQN_vBjogV5PBR5"  # Ruta al archivo
VAPID_CLAIMS = {"sub": "mailto:soporte@tcontur.com"}
ROOT_URLCONF = 'web.urls'
# settings.py
# FCM_SERVER_KEY = "TU_SERVER_KEY"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
